object Publishing {
    const val GROUP = "com.forsyth.novm"
    const val ARTIFACT_ID_RUNTIME = "novm-runtime"
    const val ARTIFACT_ID_COMPILER = "novm-compiler"
    const val VERSION = "0.8.0-SNAPSHOT"
    const val PROJ_NAME_RUNTIME = "novm runtime"
    const val PROJ_NAME_COMPILER = "novm compiler"
    const val PROJ_DESC = "ditch your ViewModels"
    const val PROJ_INCEPTION_YEAR = "2025"
    const val GITHUB_URL = "https://github.com/foooorsyth/novm/"
    const val LICENSE_NAME = "MIT License"
    const val LICENSE_URL = "https://github.com/foooorsyth/novm/blob/master/LICENSE.md"
    const val DEVELOPER_USERNAME = "foooorsyth"
    const val DEVELOPER_NAME = "Justin Forsyth"
    const val DEVELOPER_URL = "https://forsyth.com"
    const val SCM_CONNECTION = "scm:git:git://github.com/foooorsyth/novm.git"
    const val SCM_DEVELOPER_CONNECTION = "scm:git:ssh://git@github.com/foooorsyth/novm.git"
}
