name: publish-snapshot

on:
  push:
    tags:
      - 'snapshot/**'
jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish to Maven Central
      env:
        # Can't do lowercase env vars in the UI? arbitrage here
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
        SNAPSHOT: "SNAPSHOT"
      run: ./gradlew publishAllPublicationsToMavenCentralRepository
    - name: Purge Camo
      env:
        NOVM_GH_BADGE_URL: ${{ env.NOVM_GH_BADGE_URL }}
      run: echo "purging $NOVM_GH_BADGE_URL" && echo "test $TEST" && ./purge_gh_badge.sh
